boolean = True

while(boolean):
    print ("MMMMMMMMMMMMMMMMNmmmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmmddmddmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmNMMMMMMMMMMMMMMMM")
    print ("MMMMMMMMMMMMNmmmmdyydmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmmmdhyssssyhdmmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmdyydmmmNNMMMMMMMMMMMM")
    print ("MMMMMMMMMMNmmmdhsssssydmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmmdhysssyhhhhhhyssyyhdmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNddyssssshdmmmNMMMMMMMMMM")
    print ("MMMMMMMNmmmdhyssyhddysshmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmdhysssyhhhysoooosyhhhysssyhdmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmhssyddhyssyhmmmmNMMMMMMM")
    print ("MMMMNNmmmhyssshdhyosddysydmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmddhysssyhhhysoo+//////+oosyhhhysssyhdmdNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmddysydhsoyhdysssydmmmNNMMMM")
    print ("MNNmmmdysssyhhyssooooydhsshdmNNNNNNmmmmNNNNNNmmmmmmmmmmmmmmmmmmmmdmmmmmmmmmmmdhyyssyyhhhysoo++////:--://///+oosyhhhysssyhdmmmmmmmmmmmmdmmmmmmmmmmmmmmmmmmmmNNNNNNmmmNNNNNNNmdysshdyo///oshdhysssydmmmNNM")
    print ("mmmdhsssyhhhyyhdhs/hs+shdysshhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssyyhhhyoo+++///+/:-.......-/////+++osyhhhyyssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhssydhs+//////+oyhhhyssshdmmm")
    print ("mmmdysshhhyhddyo++:-ds/+ydhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhdso+++++///+/-.....----.....-:////+++++oydyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhdy+//+/////+/+osydhssydmmm")
    print ("Nmmmdyshdhhms++++++::ds//oyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy+++///+/:-.......:-...:.......-://///+++yssssssssssssssssssssssssssssssssssssyyyyyyyyyyyyyyyyyo+/+oyhys+///+//sdhsydmmmN")
    print ("Mmmmmdysddhddosyh+++-/mo///////////shhyyyyyhs//////////////////////////////////+o-///:-....---...--``-:...---.....-///-o+////////////////////////////////////dysssssysyyyyyyyyyyyys++hmhs////shdsydmmmmM")
    print ("MMNmmmdyyddhhhhhdh+/:-om+/+////++/ohm/:/++:dy/+/++///+///+////+/+////++////////+o.o-.....-:-.-:...:--:...-:.-::.....-o.o+////////+//+///////+//++///+////+//+N/::::::::::::://+////+++hmys//shdyydmmmNMM")
    print ("MMMNmmmdyydhs+/symy:::-yd///+ooo/+yms-:+syyy+/+++////+///+////+/+////+//+///+//+o.o-......-----...-://:---::-:-......o.o+//+++////+////+/////////+//++//////oNssyyyyhhd+:::hdhhhhhhy+::dmysshdyydmmmNMMM")
    print ("MMMMmmmddyydhs//symo::-:dysdyo+hssdd::/smo////++//////////////+/+//////////////+o.o-----..--:--/syyssooossyds...--:::s:o+///////////+++ossyo/+/////+++oooossyhdsoo++++ms::/Nhy++++odd//sNhhhdyydmmmmMMMM")
    print ("MMMMMNmmddyydhs/+yhm/::-+mdd+//:dhm+://dd////+o//+syo+////+oss////syyyy/+syyyys+o.oyssshs---::yhs/::::://++Ns--:dssssssyyyyyys+////odssso+ymo////dysssssoo++/oNy+/////ms:/+mhy//////yhhhhhddyydmmmNMMMMM")
    print ("MMMMMMmmmddyydhs/+yhd:::-sh++++::hs::++No/+shhyh+yNoosdo+hs+/+ho/yN+/om/ym///:sdy-sNo//sy...sdy+::oyddhhhhdN/../N::::://+++++sms///m+:///++dd+///N/:-:////++oyNyo//+//ms/++Nhy//+//////+shdyydmmmmMMMMMM")
    print ("MMMMMMMmmmddyydhs/oymo:::/++++/:-:::/+sm+ymyo+:ddmy:-od/yN/::-:hydm++oN/yN/::::/hyyNo+/yh..+mo/:/dds+:---:++.../No/:-smmdo++++md+/yh-/+ho++oNh///dhy:++/ydhhysso+//+//ms+++Nhy//+/////+shdyydmmmmMMMMMMM")
    print ("MMMMMMMMNmmmdyydhosyN/::/+++os:::::/+/dh+ydh++//dh::/mo/hN/:::::ymd//+N+sNo:::+//odNo+/dy-:my/:-ym-....--:-.----+No::/+o++osydds/+m/:+odh++/yms///oN++/:osssds///+/+//Ns+++Nhy//+/////shhyydmmmNMMMMMMMM")
    print ("MMMMMMMMMNmmmdyhdsyhm:::+++smms:::/+++No/+ydd++//:::hh//hN/::/o//os/:/NooNs-:/sy+//s+++mo.:Ns::-sm/::::::/oh:...-No:::/+++hmds+//dy:+++++++::mdo//oNo/::+oosNho/+//+//No///Nhy//+/+///sdyydmmmNMMMMMMMMM")
    print ("MMMMMMMMMMmmmdhhhyymy-:/++omyyms::+++sm///oymd+/:::om///hN/::smy++/:::msomy://dNds+++++N/.:mh::::yhsooosyysNo-..-No:::hho++sdy//+m:/++hhdy/::oNy//oN+:-ymhyyso+////+//N+::/Nhy////////sdhhdmmmMMMMMMMMMM")
    print ("MMMMMMMMMMNmmdydhyymyooo+omo/symy+oosdy//+/oymh:::/ms+//hN+:+ddddsssyhmy+mh/++mmdmhooosN:-:omh+:::/+ssso+++mh--.-Ns//oNmdho/omy/ydso+ddosN/::/dmo/sN/::hdy////////////N/::/Nhy////////sdhhdmmNMMMMMMMMMM")
    print ("MMMMMMMMMMmmmdydhsosyhhdhyo///oyhhhhyo/+/+//smy-::dh/+//ydhhhdsoyhysoo+//dmhhhmyoyddhdhs..../yddyo++oooooshmh...-hdddddy+shhdyo//oyhhmy//hhhhhhyo/odhhhdhs//+////++///myyyyNhy////////shdydmmmMMMMMMMMMM")
    print ("MMMMMMMMMMmmmdydho+//+++///++++++++++++++++odd:::smo++++oooooo++++++++++/ooooo+//+oo+///:-....:+shddddddhyo/:--//+++oo+////++///++++ooo+++oooo++++++ooooo++++++++++++++osyyyss//+////+ohdyddmmMMMMMMMMMM")
    print ("MMMMMMMMMMmmddydhso++++++shhhhhhhhhhhhhhhhhmm/::+Ndhhhhhhhhhhhhhhhhhhhhds///++//////+++/////-....-://::--..:////++++//////++///sdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhs+++/++oyhdyddmmMMMMMMMMMM")
    print ("MMMMMMMMMMmmmdhyhhhhyosyhhhdddddddddddddddmm+:::dmdddddddddddddddddyshds///++//////+++//++/////:-......-:////+++//+++//////++///sdysydddddddddddddddddddddddddddddddddddddddhhhhyooyhhhyyhdmmmMMMMMMMMMM")
    print ("MMMMMMMMMMNmmmmdhyyyhhhyyddmmmmmmmmmmmmmmmmo:::yNmmmmmmmmmmmmmmmmdhyyhdysso++////++++++y///+++/////--:////+++//+y++++++///+++sssydhyyhddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNmddyyhhhyyyhdmmmmNMMMMMMMMMM")
    print ("MMMMMMMMMMMMNmmmmmddhyyddmNMMMMMMMMMMMMMmNmo/:oNNNMMMMMMMMMMMMMmmmddhsoosyyhdhysoosyyhddh+/////++//////++////++dhdhyysossyddhyysooshddmmmMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmdhyyhddmmmmmNMMMMMMMMMMMM")
    print ("MMMMMMMMMMMMMMNmmmmmmddmNMMMMMMMMMMMMMMMmmmmmdmNMMMMMMMMMMNNNNMNmmmyoydmddhddmddhdd+odhyhho+++///+shys+///++oohhyhdo+dhhdmmddhddmdyohmmmNMNNmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmddmmmmmmNMMMMMMMMMMMMMM")
    print ("MMMMMMMMMMMMMMMMMNNNmmdMMMMMMMMMMMMMMMMMMMNNNNNMMMMMMMMMMMNmmNNNmdhdmmdhysooooydshyodddhhhmdyshddy+y+ohddhsyddhhddddohhydyoooosyhdmmdhdmNNNmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdmmNNNMMMMMMMMMMMMMMMMM")
    print ("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmmmmmNmmmmmmmhsoohmshdyssymdoodmmm+hoshyNmmdoodmyssymyydhooshmmmmmmmNmmmmmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print ("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmNNMMMNNmmmmhsmymhhyyssdosmmmm-d++msNddmoodssyyhdmymshmmmmNNMMMNNmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print ("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmMMMMMMMMMNmmmmdmhssssymoyNNmmhhyhhdNmNNsomysssshmdmmmmNMMMMMMMMMmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print ("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdmNNmmmmNNdymNmmmmmmmmmmmmNmymNNNmmmNNmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print ("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmNNNmmmmmmmNMMMNmmmmNMMMNmmmmmmmmNNmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print ("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmNNmNNNNNMMMMMMMMMMMMMMMMNNNNNNNNmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    print ("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmNMMMMMMMMMMMMMMMMMMMMMMMMMMNmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
    boolean = False
def blank_line(lines):
    for i in range(lines):
        print ("")
name = input("Hello adventurer! What is your name? ")
blank_line(1)
print ("Welcome to Wynncraft" + name + "! The text based adventure game!")
blank_line(1)
player_quest = input("What is your quest? ")
fav_color = input("And what is your favorite color? ")
